[project]
name = "backend"
version = "0.1.0"
description = "AI Application chassis - best AI app practices optimized for Azure - Backend"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi ~=0.115.6",
    "uvicorn ~=0.32.1",
    "python-dotenv ~=1.0.1",
]